### ISSUE TITLE
Test different STAC API endpoints

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#128]
Currently our stacapi unittests rely on a single endpoint (https://earth-search.aws.element84.com/v0/) and its specifications. To ensure larger flexibility of the stacapi module, we should test it accordingly on a list of different endpoints (e.g., starting from here https://stacindex.org/catalogs).

Relates to #112 , and we should only support recent versions.

**Comment by shiwakotisurendra** [comment]
I tested different endpoints as suggested  in our stacapi and i found that most of them can be accessed by different methods from our stacapi (ukis-pysat). Some are private ,some are protected , so i checked with public ones.Different endpoints needs the S3 access ID and access key. And also some endpoints cannot be accessed because of difference in method , parameters  between
