### ISSUE TITLE
`get_ts_from_sentinel_filename()` does not return a defined date format

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#42]
**Describe the bug**
`get_ts_from_sentinel_filename()` does not return a defined date format, but just a substring of the filename. It would be more useful to return something which is readable for common parsers. I would even expect this to happen and therefore label this as _bug_.

**Expected behavior**
Return a timestamp in ISO 8601 `YYYY-MM-DD`, e.g. with [`isoformat()`](https://docs.python.org/3/library/datetime.html#datetime.date.isoformat)

**Comment by nmandery** [comment]
I think it shoud return a datetime object instead of a string. That would be the appropriate type.

**Comment by fwfichtner** [comment]
> 
> I think it shoud return a datetime object instead of a string. That would be the appropriate type.

Yes, that's better.

**Comment by BoehnkeC** [comment]
Would you also like to have information about the timezone? All timestamps are GMT but do you like to have it as additional information?

**Comment by nmandery** [comment]
It should be as complete as possible - so with timezone please. Not erverybody knows about the GMT timeszone being the default for Sentinel. Also the timestamps will get used in applications where it is not clear anymore that it came from a sentinel scene and must be GMT.

**Comment by BoehnkeC** [comment]
We had some confusion with the Sentinel-2 nomenclature. Regarding the [naming conventions](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/naming-convention) for Sentinel-2, the ESA proposed this new scheme for Sentinel-2 level 1C scenes acquired since December 16, 2016:
`MMM_MSIXXX_YYYYMMDDHHMMSS_Nxxyy_ROOO_Txxxxx_<Product Discriminator>.SAFE`.

It appeared, that the omnipresent **T** was not part of the sensing timestamp anymore. However, a bit further down the new scheme was explained with this example:
`S2A_MSIL1C_20170105T013442_N0204_R031_T53NMJ_20170105T013443.SAFE` with **T** being used again as delimiter for date and time.

A check with two scenes from 2016 and 2020 revealed equal naming schemes so I assume we won't get any trouble:
`S2A_MSIL1C_20200603T103031_N0209_R108_T32UMA_20200603T155047`
`S2A_MSIL1C_20160803T103032_N0204_R108_T32UNA_20160803T103026`

@MWieland can you confirm that?

**Comment by MWieland** [comment]
Yes I can confirm the observations of @BoehnkeC . The name convention in the style `S2A_MSIL1C_20200603T103031_N0209_R108_T32UMA_20200603T155047` seems to be standard.
