### ISSUE TITLE
Create ukis_pysat.raster-Image with 2D array

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#88]
**Is your feature request related to a problem? Please describe.**

- `ukis_pysat.raster` only treats 3D arrays. Numerous extermal methods work on a 2D basis and using `np.squeeze()` or `np.expand_dims()` adds unnecessary code.

- building an `ukis_pysat.raster.Image()` from a 2D array will fail with a misleading error message:
  > rasterio._err.CPLE_FileIOError: Free disk space available is 68524220416 bytes, whereas 413266544908 are at least necessary.
  
  We could narrow this problem down to the fact, that bringing a 2D array into a 3D method is simply not working.

**Describe the solution you'd like**
Allow initalization of `ukis_pysat.raster.Image` with both 2D or 3D arrays. If I'm not mistaken, rasterio is limited to 3D arrays. @MWieland and @fwfichtner what is your opinion on this?

**Comment by fwfichtner** [comment]
I guess this happens because of how we are reading the array (without index) and [`return2d`](https://github.com/mapbox/rasterio/blob/master/rasterio/_io.pyx#L229) is therefore always `false`.
You are getting this error because when the in-memory dataset is updated we are reading the wrong number of counts (thus the memory error I guess). To fix this the way we are getting the counts should be improved and when writing the array to memory we should expand dimensions if necessary.

**Comment by MWieland** [comment]
Agree that this is a case that we should handle. Expanding dimensions may, however, be unavoidable. In my opinion this is not a problem though.

**Comment by fwfichtner** [comment]
If you only need to read in one particular band or not read in the bands at all there is no reason to not use rasterio directly.
