### ISSUE TITLE
Reduce number of dependencies

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#9]
We should try to further reduce the number of dependencies. In particular [matplotlib ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/download.py#L327) and pillow are only used in one spot and should be substituted if possible.

**Comment by fwfichtner** [comment]
I agree, particularly because they are both only needed for the [worldfile](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/download.py#L343).

Generally we might also consider providing the option of only installing substets of the package, similar to [Dask](https://docs.dask.org/en/latest/install.html#pip). We would only need to define our [extras_require](https://github.com/dlr-eoc/ukis-pysat/blob/master/setup.py#L38) similar to [how they do it](https://github.com/dask/dask/blob/master/setup.py#L10). What do you think about that?

More information about [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html). The only issue I see is that we don't have a core (defined yet).
